Algoritmo "triângulo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2022
Var
// Seção de Declarações das variáveis 
area,base,altura:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("****************************************")
escreval("Bem-vindo")
escreval("")
escreval("Programa para calcular a área do triângulo")
escreval("****************************************")

//entrada
escreval("Digite a quantidade da base do triângulo: ")
leia(base)
escreval("")
escreval("Digite a altura do triângulo: ")
leia(altura)

//processamento
area<-(base*altura)/2

//saída
escreval("A área do triângulo é de: " , area)
Fimalgoritmo