Algoritmo "MacDonalds"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/05/2022
Var
// Seção de Declarações das variáveis 
escolha_:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("Bem-vindo ao MacDonalds! Nossas opções no cardápio são: ")
escreval("1 = BigMac")
escreval("2 = Quarteirão")
escreval("3 = MacChicken")
escreval("4 = Cheddar MacMelt")
escreval("5 = MacMax")
escreval("Por favor, informe o número do seu pedido: ")
leia (escolha_)
escolha (escolha_)
caso 1
escreval ("Escolha confirmada: BigMac.")
caso 2
escreval ("Escolha confirmada: Quarteirão.")
caso 3
escreval ("Escolha confirmada: MacChicken")
caso 4
escreval ("Escolha confirmada: Cheddar MacMelt")
caso 5
escreval ("Escolha confirmada: MacMax")
outrocaso
escreval ("Não há uma opção disponível para o número digitado.")
escreval("Por favor, tente novamente.")
fimescolha





Fimalgoritmo