Algoritmo "Multiplicação"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/03/2022
Var
// Seção de Declarações das variáveis 
 nome:caractere
 Valor1:inteiro
 Valor2:inteiro
 multi:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("*********************************************************")
escreval("** Programa para calcular a multiplicação de 2 valores **")
escreval("*********************************************************")
escreval("")
escreval("Primeiro, digite seu nome: ")
leia(nome)
escreval("")
escreval("Bem vindo!," , nome ,)
escreval("")
escreval("Digite o primeiro número: ")
leia(Valor1)
escreval("Digite o segundo número: ")
leia(Valor2)
multi<- Valor1 * Valor2
escreval("A multiplicação entre ", Valor1, " e " ,Valor2, " é ", multi)

Fimalgoritmo