Algoritmo "Somatoria"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/03/2022

//Crie um algoritmo que receba 2 valores, calcule e apresente sua somatória
Var
// Seção de Declarações das variáveis 
Valor1, Valor2 :inteiro
soma : inteiro
nome : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa para calcular a somatória de 2 números")
escreval("")
escreval("Primeiro digite seu nome: ")
leia(nome)
escreval("")
escreval("Bem vindo!," , nome ,)
escreval("")
escreval("Digite o primeiro número: ")
leia(Valor1)
escreval("Digite o segundo número: ")
leia(Valor2)
soma<- Valor1 + Valor2
escreval("A soma de ", Valor1, "com" ,Valor2, " é ", soma)


Fimalgoritmo