Algoritmo "TPA"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/03/2022
Var
// Seção de Declarações das variáveis 
nome:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("************************")
escreval("**  Saudações humano  **")
escreval("************************")
escreval("")
escreval("")
escreval ("Digite seu nome:")
leia(nome)
escreval("")
escreval("")
escreval("************************")
escreval ("Boa tarde " , nome,"!")
escreval("************************")
escreval("")
escreval("Digite a quantidade de anões coletados hoje: ")
escreval("Parabéns traficante, sua média está cada vez mais aumentando!")


Fimalgoritmo