Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/04/2022
Var
// Seção de Declarações das variáveis 
brinquedo:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Escolha seu brinquedo pelo número. De 1 a 4")
leia(brinquedo)
escolha(brinquedo)
 caso 1
  escreval("O brinquedo é montanha russa")
 caso 2
  escreval("Roda Gigante")
 caso 3
  escreval("Kamikaze")
 caso 4
  escreval("Carrinho de batida")
 outrocaso
  escreval("Brinquedo em manutenção")
fimescolha

Fimalgoritmo