Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2022
Var
// Seção de Declarações das variáveis 
n1,n2,md:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa para cálcular a média do aluno")
escreval("Digite a primeira nota: ")
leia(n1)
escreval("Digite a segunda nota: ")
leia(n2)
md <- (n1+n2)\2
se(md>=5) entao
  escreva("O aluno alcançou a média para aprovação")
  senao
  escreva("O aluno alcançou a média para aprovação")
  Fimse

Fimalgoritmo
