Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2022
Var
// Seção de Declarações das variáveis 
senha:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa para validação de senha")
escreva("Digite sua senha: ")
leia(senha)
se (senha=1234) entao
 escreval("Senha correta!")
senao
 escreval("Senha incorreta!")
fimse

Fimalgoritmo