Algoritmo "Algoritmo 4"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2022
Var
// Seção de Declarações das variáveis 
area,r:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa para cálcular a área do círculo")
escreval("")
escreval("Digite o valor do raio: ")
leia(r)
escreval("")
area<-pi*(r*r)
escreval("O valor da área do círculo é " , area)

Fimalgoritmo