Algoritmo "Algoritmo 5"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2022
Var
// Seção de Declarações das variáveis 
 a,b,m:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa para cálcular a média dos valores")
escreval("")
escreval("Digite o valor para a variável: ")
leia(a)
escreval("")
escreval("Digite o valor para a variável: ")
leia(b)
M<-(a+b)/2
escreval("a média dos valores é: " , M)

Fimalgoritmo