Algoritmo "Algoritmo 3"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2022
Var
// Seção de Declarações das variáveis 

a, valor:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa para cálcular o número ao quadrado")
escreval("")
escreval("Digite o número: ")
leia(a)
escreval("")
valor<-a*a
escreval("O valor do número ao quadrado é" , valor)

Fimalgoritmo