Algoritmo "Algoritmo 6"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2022
Var
// Seção de Declarações das variáveis 
 peso,altura,imc:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa para cálcular o seu imc")
escreval("")
escreval("Digite o seu peso: ")
leia(peso)
escreval("")
escreval("Digite a sua altura")
leia(altura)
imc<-peso/(altura*altura)
escreval("Seu imc é igual a" , imc)

Fimalgoritmo