Algoritmo "Algoritmo 2"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2022
Var
// Seção de Declarações das variáveis 
a, b, soma:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Programa para cálculo de soma entre dois números")
escreval("")
escreval("Digite o primeiro valor: ")
leia(a)
escreval("Digite o segundo valor: ")
leia(b)
escreval("")
soma<-a+b
escreval("O valor da soma é" , soma)

Fimalgoritmo