Algoritmo "Algoritmo 1"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2022
Var
// Seção de Declarações das variáveis 
a, perimetro:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Programa para cálcular o perimetro")
escreval("")
escreval("Digite o valor do lado: ")
leia(a)
escreval("")
perimetro<-4*a
escreval("O valor do perimetro é" , perimetro)

Fimalgoritmo