Algoritmo "Algoritmo 7"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2022
Var
// Seção de Declarações das variáveis 
Celsius,Kelvin:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa para converter de Celsius para Kelvin")
escreval("")
escreval("Digite a temperatura em Celsius: ")
leia(Celsius)
escreval("")
Kelvin<-Celsius+273,15
escreval("O valor da temperatura de Celsius para Kelvin é " , Kelvin)

Fimalgoritmo